# Generated by Django 3.2 on 2021-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="body",
            field=models.CharField(max_length=250),
        ),
    ]
