# Generated by Django 3.2 on 2022-01-07 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211231_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
