# Generated by Django 3.2 on 2021-10-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_auto_20211030_1829"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_body", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WrittenQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.question",
                    ),
                ),
                ("question_body", models.CharField(max_length=200)),
            ],
            bases=("polls.question",),
        ),
        migrations.RenameField(
            model_name="poll",
            old_name="questions",
            new_name="question",
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.question",
                    ),
                ),
                ("question_body", models.CharField(max_length=200)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.multiplechoiceanswer",
                    ),
                ),
            ],
            bases=("polls.question",),
        ),
    ]
