# Generated by Django 3.2 on 2022-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
