# Generated by Django 3.2 on 2022-01-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
