# Generated by Django 3.2 on 2021-10-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_auto_20211030_1836"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multiplechoicequestion",
            old_name="reporter",
            new_name="multiple_choice_answer",
        ),
    ]
