# Generated by Django 3.2 on 2021-11-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_rename_reporter_multiplechoicequestion_multiple_choice_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="title",
        ),
    ]
