# Generated by Django 3.2 on 2022-01-27 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.submission'),
        ),
    ]
