# Generated by Django 3.2 on 2021-11-04 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_alter_multiplechoicequestion_multiple_choice_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="multiple_choice_answer",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="question",
        ),
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="multiple_choice_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="polls.multiplechoicequestion",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="poll",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
            ),
        ),
    ]
