# Generated by Django 3.2 on 2021-11-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20211103_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='question_body',
        ),
        migrations.RemoveField(
            model_name='writtenquestion',
            name='question_body',
        ),
    ]
